<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="MimeTypes" />
		<PackageReference Include="Kiyote.Geometry" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\..\src\Common\Core\Common.Core.Abstractions\Common.Core.Abstractions.csproj" />
	</ItemGroup>

</Project>
