name: Deploy

on:
  push:
    branches: main
    paths:
    - '**.tf'
    - '.github/workflows/deploy.yml'
  pull_request:
    paths:
    - '**.tf'
    - '.github/workflows/deploy.yml'
  create:
    branches: 
      - release/**

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
  TERRAFORM_VERSION: 1.1.3

jobs:
  plan:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        environment: [dev, prod]
      fail-fast: true
    environment: ${{ matrix.environment }}
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: hashicorp/setup-terraform@v1
        with:
           terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Init
        run: terraform init -backend-config=access_key="${{ secrets.AWS_ACCESS_KEY_ID }}" -backend-config=secret_key="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        working-directory: terraform/environments/${{ matrix.environment }}

      - name: Terraform Validate
        run: terraform validate -no-color
        working-directory: terraform/environments/${{ matrix.environment }}

      - name: Terraform Plan
        run: terraform plan -no-color
        working-directory: terraform/environments/${{ matrix.environment }}

  deploy_dev:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: plan
    if: (github.ref == 'refs/heads/main')
    
    steps:
    - name: Deploy
      run: terraform apply
      working-directory: terraform/environments/dev

  deploy_prod:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: plan
    if: (startsWith(github.ref, 'ref/heads/release'))
    
    steps:
    - name: Deploy
      run: terraform apply
      working-directory: terraform/environments/prod